import streamlit as st
from PIL import Image

def red_intro():
    red_image = Image.open('red wine.jpg')
    image_placeholder = st.empty()
    caption_placeholder = st.empty()
    image_placeholder.image(red_image, caption='Image by MATT TAYLOR-GROSS', use_column_width=True)
    st.write("Red Wine is made from dark-colored grape varieties and derives its distinct hue from the grape skins during the fermentation process. Red wines come in a wide range of styles, flavors, and aromas, influenced by factors like grape type, winemaking techniques, and the region of origin. Whether you're savoring a bold Cabernet Sauvignon, a smooth Merlot, or a delicate Pinot Noir, red wine offers a complex spectrum of tastes, from fruity and floral notes to earthy and spicy undertones. It is often celebrated for its ability to enhance the dining experience, pairing beautifully with a variety of foods, making it a versatile and beloved choice among wine enthusiasts worldwide.")

def cab():
    st.title("Cabernet Sauvignon")
    cab_image = Image.open('cab.jpg')
    image_placeholder = st.empty()
    caption_placeholder = st.empty() 
    image_placeholder.image(cab_image, caption='Image by SILVEROAK', use_column_width=True)
    st.write("**Style & Structure:**")
    st.write("Cabernet Sauvignon is renowned for its bold, full-bodied style and robust structure. This red wine typically boasts deep, dark coloration and offers a complex flavor profile dominated by blackcurrant, plum, and sometimes herbal or cedar notes. Its firm tannins contribute to a solid structure and potential for aging, often developing additional nuances of leather, tobacco, and spice over time.")
    st.write("")
    st.write("**Wine Regions:**")
    st.write("1. Bordeaux, France: Bordeaux is perhaps the most renowned region for Cabernet Sauvignon, especially in the subregions of the Médoc, Pauillac, Margaux, and Saint-Julien. It's often blended with Merlot, Cabernet Franc, and other varietals to create Bordeaux blends.")
    st.write("2. Napa Valley, California, USA: Napa Valley is celebrated for its premium Cabernet Sauvignon wines, known for their bold and robust character. The Oakville and Rutherford AVAs are particularly famous.")
    st.write("3. Sonoma County, California, USA: Within Sonoma, regions like Alexander Valley and Knights Valley produce excellent Cabernet Sauvignon wines.")
    st.write("4. Coonawarra, South Australia: This Australian region is renowned for its Cabernet Sauvignon, characterized by its distinctive 'terra rossa' red soil.")
    st.write("5. Maipo Valley, Chile: Maipo Valley is known for its exceptional Cabernet Sauvignon, often featuring ripe fruit flavors and a solid structure.")
    st.write("6. Stellenbosch, South Africa: Stellenbosch is one of South Africa's premier wine regions, producing high-quality Cabernet Sauvignon wines with a unique sense of terroir.")
    st.write("7. Tuscany, Italy: While Cabernet Sauvignon is not the primary grape in Tuscany, it is used in some Super Tuscan blends, adding depth and complexity.")
    st.write("8. Washington State, USA: Regions like Walla Walla Valley and Red Mountain in Washington State are gaining recognition for their Cabernet Sauvignon wines.")
    st.write("")
    st.write("**Food Pairing:**")
    st.write("Cabernet Sauvignon pairs exceptionally well with rich and hearty dishes. Its bold structure and flavors complement red meat like steak and lamb, making it an ideal choice for grilled or roasted meats. Additionally, it harmonizes with strong cheeses, dark chocolate, and dishes featuring earthy herbs and spices.")

def merlot():
    st.title("Merlot")
    merlot_image = Image.open('merlot.jpg')
    image_placeholder = st.empty()
    caption_placeholder = st.empty() 
    image_placeholder.image(merlot_image, caption='Image by ©wjarek', use_column_width=True)
    st.write("**Style & Structure:**")
    st.write("Merlot is known for its approachable and versatile style. It typically offers a softer and smoother profile compared to Cabernet Sauvignon. With a medium to full body, it showcases flavors of red and black fruits, such as plum, cherry, and sometimes hints of chocolate or herbs. Merlot's tannins are milder, resulting in a more supple texture. It often exhibits a pleasant, velvety mouthfeel. This wine can range from easy-drinking and fruit-forward to more complex and age-worthy, depending on the region and winemaking techniques. Merlot is an excellent choice for those seeking a balanced and accessible red wine.")
    st.write("")
    st.write("**Wine Region:**")
    st.write("1. Bordeaux, France: Merlot is a key component in many Bordeaux blends, especially in the Right Bank regions of Pomerol and Saint-Émilion.")
    st.write("2. Napa Valley, California, USA: Napa Valley produces high-quality Merlot wines, often characterized by ripe fruit flavors and a soft, supple texture.")
    st.write("3. Sonoma County, California, USA: Merlot is also successfully cultivated in Sonoma, particularly in regions like Alexander Valley and Knights Valley.")
    st.write("4. Tuscany, Italy: Merlot is used in Super Tuscan blends, adding richness and roundness to the wines.")
    st.write("5. Washington State, USA: Regions like Columbia Valley in Washington State are known for producing Merlot with lush fruit flavors and a balanced structure.")
    st.write("6. Chile: Chilean Merlot is celebrated for its approachability and affordability, with notable examples coming from regions like Maipo Valley and Colchagua Valley.")
    st.write("7. South Australia: Merlot is grown in various South Australian regions, contributing to both blends and varietal wines.")
    st.write("8. Hawke's Bay, New Zealand: New Zealand's Hawke's Bay region produces Merlot wines with bright fruit character and a distinctive regional style.")
    st.write("")
    st.write("**Food Pairing:**")
    st.write("Merlot's versatile and approachable nature makes it a great match for a variety of dishes. It pairs wonderfully with roasted or grilled meats, such as lamb or pork, as well as pasta dishes with tomato-based sauces. Soft cheeses, mushrooms, and dishes featuring herbs like rosemary also complement Merlot's fruit-forward flavors.")